name: "Hotfix Slack Notification"
description: "Notify Slack when a hotfix PR is merged"
author: "chowdharyshivi"

inputs:
  pr_title:
    description: "PR title"
    required: true
  pr_url:
    description: "PR URL"
    required: true
  slack_token:
    description: "Slack bot token"
    required: true
  linear_api_key:
    description: "Linear API Key"
    required: true
  slack_channel:
    description: "Slack Channel ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
      shell: bash

    - name: Run Python script
      run: |
        source .venv/bin/activate
        python main.py
      shell: bash
