name: "Post Hotfix Confirm"
description: "A custom GitHub Action to send Slack notifications to validate if hotfixes are getting tested."

inputs:
  pr_title:
    description: "Title of the GitHub Pull Request"
    required: true
  pr_url:
    description: "URL of the Pull Request"
    required: true
  slack_token:
    description: "Slack Bot Token"
    required: true
  slack_channel:
    description: "Slack Channel to send the message"
    required: true
  linear_api_key:
    description: "API Key for Linear"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash

    - name: Run Python Script
      run: python main.py
      shell: bash
      env:
        PR_TITLE: ${{ inputs.pr_title }}
        PR_URL: ${{ inputs.pr_url }}
        SLACK_TOKEN: ${{ inputs.slack_token }}
        SLACK_CHANNEL: ${{ inputs.slack_channel }}
        LINEAR_API_KEY: ${{ inputs.linear_api_key }}

