name: Hotfix PR Slack Notifier

on:
  pull_request:
    types: [closed]

jobs:
  notify_hotfix:
    if: github.event.pull_request.merged == true  # Runs only if PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Use Hotfix Slack Action
        uses: chowdharyshivi/post-hotfix-notify@main
        with:
          pr_title: ${{ github.event.pull_request.title }}
          pr_url: ${{ github.event.pull_request.html_url }}
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          linear_api_key: ${{ secrets.LINEAR_API_KEY }}
          slack_channel: "your-slack-channel"
